# 应用的端口号
server:
  port: 82

# 给应用起个名字
spring:
  application:
    name: user-client

# 将我们的client注册到Eureka中
eureka:
  client:
    register-with-eureka: true # 是否注册自己的信息到EurekaServer，默认是true
    # 消费者拉取服务列表的时间 默认30秒拉取一次
    registry-fetch-interval-seconds: 5
    fetch-registry: true # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:81/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

# Ribbon策略和超时配置
user-server:
  ribbon:
    # 将Ribbon负载均衡策略设置为随机
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    # Ribbon(负载均衡)超时配置
    ConnectTimeout: 250 # Ribbon的连接超时时间(ms)
    ReadTimeout: 1000 # Ribbon的数据读取超时时间(ms)

# 开启Feign的熔断功能
feign:
  hystrix:
    enabled: true
