spring:
  mail:
    # 邮箱账户
    username: 503899856@qq.com
    # 授权码
    password: jcltnjqmmqhgbgbi
    # 邮箱服务器
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            # 安全验证
            enable: true
          auth: true
          # 服务开启配置
          starttls:
            enable: true
            required: true
    # 邮箱的端口
    port: 465
    default-encoding: UTF-8
