# 端口号
server:
  port: 80

# mysql连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root1234

# redis 连接配置
  redis:
    host: 10.21.40.53
    port: 6379
    password: 1234
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8

# mybatis读取mapper配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  typeAliasesPackage: com.noah.financial.cloud.demo

mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml

# Quartz(定时任务)
org:
  quartz:
    # 调度器配置
    scheduler:
      tablePrefix: QRTZ_   # 表的前缀
      isClustered: true     # 是否集群
      clusterCheckinInterval: 2000  # 检入频率
      instanceName: springBootDemoQuartzShcheduler  # 调度器名称
      instanceId: AUTO # 调度器ID

    # 储存信息配置
    jobStore:
      class: org.quartz.impl.jdbcjobstore.JobStoreTX # 配置事务
      driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate # 配置连接数据库类型

    # 数据源配置
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool # 配置线程池
      threadCount: 20 # 线程数
      threadPriority: 5 # 线程优先级
      threadsInheritContextClassLoaderOfInitializingThread: true # 是否从外部继承

#调用kyz接口参数配置
kyz.host: xxx
kyz.token: xxxx